# --- Core Hugo Settings ---
baseURL: "https://pestpolicy.com/"
languageCode: "en-us"
title: "Home Improvement Guides"
theme: "PaperModX"

enableRobotsTXT: true
enableSitemap: true

buildDrafts: false
buildFuture: false
buildExpired: false

# --- Output Formats ---
outputs:
  home: ["HTML", "RSS", "JSON", "robotsTXT"]
  page: ["HTML"]
  section: ["HTML", "RSS"]
  sitemap: ["XML"]

outputFormats:
  XML:
    name: "Sitemap"
    mediaType: "application/xml"
    baseName: "sitemap"
    isPlainText: true
    notAlternative: true

  robotsTXT:
    name: "robotsTXT"
    mediaType: "text/plain"
    baseName: "robots"
    isPlainText: true
    notAlternative: true

# --- Permalinks and Taxonomies ---
permalinks:
  posts: "/:slug/"

taxonomies:
  tag: "tags"
  category: "categories"

slug:
  ugly: false

# --- Theme Parameters ---
params:
  env: "production"
  defaultTheme: "auto"
  disableSpecial1stPost: false
  disableScrollToTop: false
  title: "Home Improvement Guides"
  description: "Pest solutions, sprayers and paint. Visit the [Product Reviews](/categories/product-reviews/) or check out the [DIY Guides](/categories/guide/)"
  robots: "index, follow"

  homeInfoParams:
    Title: "Home Improvement | Bugs, Paint, & Shoes"
    Content: |
      Welcome to Pestpolicy. Insights into bugs control, DIY painting, and Shoes - reveal how pests can affect painted surfaces and the performance of spray equipment. Understanding the interaction between paint types and sprayer technology is essential for achieving smooth, durable finishes.

      Proper maintenance of sprayers and selecting the right paint formulation can also minimize issues caused by bugs during and after application.
      Visit the [Product Reviews](/categories/product-reviews/) or check out the [DIY Guides](/categories/guide/).

  analytics:
    google:
      SiteVerificationTag: "wcIIamJKWxC3IcPXe02IZlAEWcGk828ZThxeK1w3aUQ"

  anonymizeIP: true

  imaging:
    quality: 85
    webp: true

# --- Sitemap Settings ---
sitemap:
  changefreq: "weekly"
  priority: 0.7
  filename: "sitemap.xml"
  disable: false

# --- Build Settings ---
build:
  errorOnMissingPagePermalinks: true
  errorOnInvalidPermalinks: true
  writeStats: true
  useResourceCacheWhen: "always"
  noChmod: true
