# ===== Core Settings =====
baseURL: 'https://pestpolicy.com/'
languageCode: 'en-us'
title: 'GUIDES'
theme: "PaperModX"
enableRobotsTXT: true
enableGitInfo: true

# ===== Turbo Indexing Setup =====
build:
  writeStats: true
  useResourceCacheWhen: always
  noJSConfigInAssets: true

outputs:
  home: ["HTML", "RSS", "JSON", "WebAppManifest"]
  page: ["HTML", "AMP"]
  section: ["HTML", "RSS"]
  taxonomy: ["HTML", "RSS"]

sitemap:
  changefreq: "daily"
  priority: 1.0
  filename: "sitemap.xml"
  lastmod: true

# ===== Verification & Indexing Services =====
services:
  googleSearchConsole:
    enable: true
    verify_google: "wcIIamJKWxC3IcPXe02IZlAEWcGk828ZThxeK1w3aUQ"
  
  googleAnalytics:
    enable: true
    id: "G-XXXXXXXXXX"
  
  googleTagManager:
    enable: true
    id: "GTM-XXXXXX"
  
  instantPage:
    enable: true

# ===== SEO Overdrive =====
params:
  env: "production"
  
  # Verification
  seo:
    googleSiteVerification: "wcIIamJKWxC3IcPXe02IZlAEWcGk828ZThxeK1w3aUQ"
    bingSiteVerification: "YOUR_BING_CODE"
  
  # Metadata
  description: "Professional pest control guides, product reviews, and extermination techniques. Expert advice updated daily."
  keywords: ["pest control", "exterminator", "sprayer reviews", "DIY pest solutions"]
  
  # Indexing Boosters
  noindex: false
  canonicalURL: true
  opengraph: true
  twitterCards: true
  schema: true
  
  # Performance
  minify: true
  preload: true
  preconnect: ["https://fonts.gstatic.com", "https://cdn.jsdelivr.net"]

# ===== Navigation =====
menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1
    
    - identifier: "guides"
      name: "Guides"
      url: "/guides/"
      weight: 2
    
    - identifier: "reviews"
      name: "Reviews"
      url: "/reviews/"
      weight: 3
    
    - identifier: "categories"
      name: "Categories"
      url: "/categories/"
      weight: 4

# ===== Content Organization =====
taxonomies:
  category: "categories"
  tag: "tags"
  topic: "topics"

permalinks:
  posts: "/:year/:month/:slug/"
  categories: "/category/:slug/"
  tags: "/tag/:slug/"

# ===== Technical SEO =====
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 4
  highlight:
    style: "github"
  image:
    lazy: false
    quality: 80

# ===== Cache Settings =====
caches:
  assets:
    maxAge: 31536000
  resources:
    maxAge: 86400