# --- Basic Site Configuration (for Home Improvement Guides / pestpolicy.com) ---
# The base URL for your deployed website.
# For Netlify deployment, ensure this matches your site's URL.
# It's often best to manage this via Netlify build settings or netlify.toml
# to handle different deploy URLs (e.g., deploy previews vs production).
baseURL: "https://pestpolicy.com/"

languageCode: "en-us" # Your site's language code
title: "Home Improvement Guides" # Your website's main title
theme: 'hugo-PaperMod' # Ensure this matches the exact name of the theme folder in your 'themes' directory. Note: This is 'hugo-PaperMod', not 'PaperModX'.

enableRobotsTXT: true # Enables robots.txt generation for SEO
enableSitemap: true # Enables sitemap generation for SEO

# Define output formats for different page types
outputs:
  home: ["HTML", "RSS", "JSON", "robotsTXT"] # Homepage outputs
  page: ["HTML"] # Standard page outputs
  section: ["HTML", "RSS"] # Section (list) page outputs
  sitemap: ["XML"] # Sitemap output

# Define custom output formats (used above)
outputFormats:
  XML:
    name: "Sitemap"
    mediaType: "application/xml"
    baseName: "sitemap"
    isPlainText: true
    notAlternative: true

  robotsTXT:
    name: "robotsTXT"
    mediaType: "text/plain"
    baseName: "robots"
    isPlainText: true
    notAlternative: true

# Build settings to exclude drafts, future, and expired content in production builds
buildDrafts: false
buildFuture: false
buildExpired: false

# Define taxonomies (how content is categorized and tagged)
taxonomies:
  tag: 'tags' # Content can have 'tags'
  category: 'categories' # Content can have 'categories'

# Define permalink structure for different content types
permalinks:
  posts: "/:slug/" # Posts will have URLs like /post-title/

slug:
  ugly: false # Use clean URLs (not /post.html)

# --- Theme-Specific Parameters (PaperMod - Original Theme) ---
# Found within the 'params:' section. Edit these for your site.
params:
  env: 'production' # Set environment to production for live site builds
  defaultTheme: 'auto' # Use auto theme based on user system preference
  disableSpecial1stPost: false # Control special styling for the first post
  disableScrollToTop: false # Control the scroll-to-top button

  # Site Metadata for SEO and theme display
  title: "Home Improvement Guides" # Often used in the header/title bar (can be same as main title)
  description: "Pest solutions, sprayers and paint. Visit the [Product Reviews](/categories/product-reviews/) or check out the [DIY Guides](/categories/guide/)" # Site description
  robots: "index, follow" # Robots meta tag content

  # Homepage Info / Banner Configuration (PaperMod theme)
  homeInfoParams:
    Title: "Home Improvement | Bugs, Paint, & Shoes" # Homepage banner title
    Content: |
      Welcome to Pestpolicy. Insights into bugs control, DIY painting, and Shoes - reveal how pests can affect painted painted surfaces and the performance of spray equipment. Understanding the interaction between paint types and sprayer technology is essential for achieving smooth, durable finishes.

      Proper maintenance of sprayers and selecting the right paint formulation can also minimize issues caused by bugs during and after application.
      Visit the [Product Reviews](/categories/product-reviews/) or check out the [DIY Guides](/categories/guide/).
      # This section defines the main content displayed in the homepage banner.

  # Analytics Configuration (Google Analytics)
  analytics:
    google:
      SiteVerificationTag: "wcIIamJKWxC3IcPXe02IZlAEWcGk828ZThxeK1w3aUQ" # Google Site Verification tag

  anonymizeIP: true # Anonymize IP addresses for analytics

  # Image Processing Settings
  imaging:
    quality: 85 # Image quality for processing
    webp: true # Enable WebP image format

# Sitemap configuration (can also be defined at the top level)
sitemap:
  changefreq: "weekly" # Frequency of changes for sitemap
  priority: 0.7 # Priority for pages in sitemap
  filename: "sitemap.xml" # Sitemap filename
  disable: false # Enable sitemap generation

# Build settings (can also be defined at the top level)
build:
  errorOnMissingPagePermalinks: true # Error if permalink is missing
  errorOnInvalidPermalinks: true # Error if permalink is invalid
  writeStats: true # Write build statistics
  useResourceCacheWhen: "always" # Use resource cache
  noChmod: true # Disable chmod

# --- Site Menu Configuration (Edit these for your navigation) ---
# Defines the links that appear in your site's main menu.
menu:
  main:
    - name: Blog # Menu item text
      url: /posts/ # URL the menu item links to
      weight: 1 # Order of the menu item

    - name: Fleas
      url: /categories/fleas/
      weight: 2

    - name: Product Reviews
      url: /categories/product-reviews/
      weight: 3

    - name: Guides
      url: /categories/guide/
      weight: 4
    # Add more menu items as needed

# --- End of config.yaml for Home Improvement Guides ---
