# --- Basic Site Configuration (Edit these for Sleepy to Rested) ---
baseURL: 'https://pestpolicy.com/' # Your website's base URL
languageCode: 'en-us' # Your language code
title: 'Sleepy to Rested' # Your website's title
theme: "PaperModX" # Make sure this is "PaperModX"

permalinks:
  posts: "/:slug/"

homeInfoParams:
    Title: "PaperModX"
    Content: |
      Welcome to demo of hugo's theme PaperModX.

      - **PaperModX** is a simple but fast and responsive theme with useful feature-set that enhances UX.

      - PaperModX is based on theme [PaperMod](https://github.com/adityatelange/hugo-PaperMod).

      To get started, please head to the [Docs](docs).

      To see examples of different contents, head to [examples tag](tags/example).

# --- Theme-Specific Parameters (PaperModX) ---
# Found within the [params] or 'params:' section. Edit these for your site.
params:
  env: "production" # Keep as "production" for live site builds
  description: "Your guide to moving from sleepy to genuinely rested." # Your site's description
  keywords: # Your site's keywords
    - sleep
    - rest
    - quality sleep
    - sleep health
    - insomnia
    - bedroom environment
    # Add more relevant keywords
  author: "Elizabeth" # Your author name
  # You might see other author/profile related params here

  # Date format throughout the site
  DateFormat: "January 2, 2006" # Example format

  # Default theme (light, dark, or auto)
  defaultTheme: "light" # or "dark" or "auto"

  # Disable theme toggle (if you only want one theme)
  # disableThemeToggle: true

  # Enable / Disable specific features globally
  ShowShareButtons: true # Show social share buttons on articles
  ShowReadingTime: true # Show estimated reading time on articles
  ShowPostNavLinks: true # Show previous/next post links at the end of articles
  ShowRssButtonLeafBundle: false # Usually false unless you have specific RSS needs
  ShowToc: true # Enable Table of Contents by default for pages/posts

  # This is often for the profile mode on the homepage (see PaperModX docs)
  # profileMode:
  #   enabled: false # Set to true to enable profile mode
  #   title: "Sleepy to Rested" # Title in profile mode
  #   subtitle: "Your journey to better sleep starts here." # Subtitle
  #   imageUrl: "path/to/your/profile/image.jpg" # Path to your image
  #   imageZoom: false # Zoom effect on image
  #   imageCircleIcons: true # Circle icons below image
  #   imageWidth: 125 # Image width
  #   imageHeight: 125 # Image height
  #   buttons:
  #     - name: "Articles"
  #       url: "/posts/"
  #     - name: "About"
  #       url: "/about/"

  # Homepage layout settings (often within params or a sub-section)
  # You might see settings related to listing posts here
  # homeInfoParams: # Another section for homepage content/layout
  #   Title: "Welcome to Sleepy to Rested"
  #   Content: "Your guide to achieving genuine quality sleep. We help you go from feeling sleepy to being truly rested through practical tips and advice."

  # Social Icons (usually at the bottom/footer)
  # socialIcons:
  #   - name: "linkedin"
  #     url: "your-linkedin-profile-url" # Replace with your URL
  #   - name: "github"
  #     url: "your-github-profile-url"   # Replace with your URL
  #   - name: "twitter"
  #     url: "your-twitter-profile-url" # Replace with your URL
  #   # Add other social media links as needed

  # You'll find many other parameters for things like:
  # analytics: (for Google Analytics or other tracking)
  # assets: (settings for CSS/JS assets)
  # fuseOpts: (settings for the built-in search, if enabled)
  # cover: (settings for cover images on posts)
  # label: (label/icon in header)


# --- Site Menu Configuration (Edit these for your navigation) ---
menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 10

    - identifier: "articles"
      name: "Articles"
      url: "/posts/" # Make sure this matches where your articles are
      weight: 20

    - identifier: "about"
      name: "About"
      url: "/about/" # Make sure this matches your about page URL
      weight: 30

    # Add more menu items as needed for Categories, Tags, etc.
    # Look at the example site's menu config for ideas.


# --- Other Hugo/PaperModX Sections You Might See ---
# outputs: # Configure output formats (HTML, RSS, JSON, etc.)
#   home: ["HTML", "RSS", "JSON"]
#   page: ["HTML", "AMP"] # Example for AMP
#   section: ["HTML", "RSS"]
#   taxonomy: ["HTML", "RSS"]
#   term = ["HTML", "RSS"]

# taxonomies: # Define custom taxonomies if needed
#   category: "categories"
#   tag: "tags"
#   series: "series"

# markup: # Configure markdown rendering settings
#   # Example: Enable and configure table of contents specifically via markup
#   tableOfContents:
#     startLevel: 2
#     endLevel: 3
#     ordered: true

# sitemap: # Sitemap configuration for SEO
#   changefreq: "weekly"
#   priority: 0.5

# privacy: # Privacy settings (e.g., for embedded content)

# services: # Configure external services (e.g., for analytics)


# --- End of Representative config.yaml ---